language: rust
dist: trusty

os:
- linux
- osx
- windows

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: false

cache: cargo

script:
  - cargo test --release
  - cargo build
