language: rust
dist: trusty
sudo: true

os:
- linux

rust:
  - stable

install:
  - rustup component add rustfmt
  - rustup component add clippy

script:
  - cargo fmt -- --check
  - cargo clippy
  - cargo test --release
