language: rust
dist: trusty
sudo: true

os:
- linux
- windows

rust:
  - stable

install:
  - rustup component add rustfmt
  - rustup component add clippy
  - rustfmt -V

script:
  - cargo fmt --all -- --check
  - cargo clippy
  - cargo test --release
